name: Configuración de RDP en Windows

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Mostrar versión de Windows
      run: |
        echo "Versión de Windows:"
        systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

    - name: Habilitar puerto 3389
      run: |
        echo "Habilitando puerto 3389..."
        netsh advfirewall firewall add rule name="Abrir puerto 3389" protocol=TCP dir=in localport=3389 action=allow

    - name: Crear usuario para RDP
      run: |
        echo "Creando usuario para RDP..."
        net user rdpuser Password123! /add
        net localgroup Administrators rdpuser /add

    - name: Habilitar Escritorio Remoto
      run: |
        echo "Habilitando Escritorio Remoto..."
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f

    - name: Mostrar credenciales y detalles de conexión RDP
      run: |
        echo "Credenciales para RDP:"
        echo "Usuario: rdpuser"
        echo "Contraseña: Password123!"
        echo "Dirección IP del equipo:"
        ipconfig | findstr /R /C:"IPv4 Address"
