name: Show Windows Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  show-windows-version:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Windows version
      run: |
        systeminfo | findstr /B /C:"OS Name" /C:"OS Version"


    - name: Display Network Name
      run: |
        netsh wlan show interfaces | findstr /R "^ *SSID"
